application: longerreads
version: 1
runtime: python
api_version: 1

handlers:

################################################################################
# Queue Tasks Stuff
################################################################################

- url: /tasks/fetch_articles
  script: tasks/fetch_articles.py
  login: admin


################################################################################
# Pages
################################################################################

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /imgs
  static_dir: imgs

- url: /fonts
  static_dir: fonts

- url: .*
  script: index.py
  login: admin
