application: longerreads
version: 1
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py  


################################################################################
# Queue Tasks Stuff
################################################################################

- url: /tasks/fetch_articles
  script: tasks/fetch_articles.py
  login: admin

- url: /tasks/publish_article
  script: tasks/publish_article.py
  login: admin



################################################################################
# API pages
################################################################################

- url: /api/lr.article.approve
  script: api/lr.article.approve.py
  login: admin

- url: /api/lr.article.unapprove
  script: api/lr.article.unapprove.py
  login: admin

- url: /api/lr.article.reject
  script: api/lr.article.reject.py
  login: admin

- url: /api/lr.get.news
  script: api/lr.get.news.py

- url: /api/lr.get.approved
  script: api/lr.get.approved.py

- url: /api/lr.get.published
  script: api/lr.get.published.py



################################################################################
# Pages
################################################################################

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /imgs
  static_dir: imgs

- url: /fonts
  static_dir: fonts

- url: /for_men
  script: for_men.py

- url: /lastweek
  script: lastweek.py

- url: /kindle
  script: kindle.py

- url: /wordcount
  script: wordcount.py

- url: .*
  script: index.py
  login: admin
