application: longerreads
version: 1
runtime: python
api_version: 1

handlers:



################################################################################
# Queue Tasks Stuff
################################################################################

- url: /tasks/fetch_articles
  script: tasks/fetch_articles.py
  login: admin

- url: /tasks/publish_article
  script: tasks/publish_article.py
  login: admin



################################################################################
# API pages
################################################################################

- url: /api/lr.article.approve
  script: api/lr.article.approve.py
  login: admin

- url: /api/lr.article.unapprove
  script: api/lr.article.unapprove.py
  login: admin

- url: /api/lr.article.reject
  script: api/lr.article.reject.py
  login: admin



################################################################################
# Pages
################################################################################

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /imgs
  static_dir: imgs

- url: /fonts
  static_dir: fonts

- url: .*
  script: index.py
  login: admin
